### ISSUE TITLE
CoreOS v1632.2.1 - [STABLE] Cloud-Init no longer working with no warning

### ISSUE THREAD

**Issue by qrpike** [coreos/container-images#3]
There is no where else to post this issue about CoreOS image.

I recently updated to v1632.2.1 [STABLE] branch, and cloud-init just stopped working. 

There was no warning of this in the release notes, and is a pretty important thing to remove from a stable release without warning.

**Comment by lucab** [comment]
The relevant bug tracker for this kind of issues is https://github.com/coreos/bugs.

Please open a report there, attaching all relevant journal logs and details about your environment. To the best of my knowledge cloud-init support has not been removed yet, so this is likely just a bug.

In general however we recommend not to rely on it anymore due to its design limitations, but to follow best-practices described at https://coreos.com/os/docs/latest/provisioning.html instead.

I'm closing this here, feel free to followup with details on the bug tracker.
